### PR TITLE
Add a -remove flag to remove a single actor from a list

### PR DESCRIPTION
**Pull request by isaac-gittins-amaysim**
This PR will allow a user to remove a single actor from a list.

EG:

    $ repsheet -blacklist="1.1.1.1" -remove
    $ repsheet -whitelist="2.2.2.2" -remove
    $ repsheet -mark="3.3.3.3" -remove

### CODE REVIEW

**Comment by isaac-gittins-amaysim** [comment]
I am a newbie to GitHub, so let me know if I haven't done this the correct way.

Regards
Isaac

**Comment by abedra** [comment]
Thanks for sending! I think it would be best to make remove be a string argument that stands on its own. That way you don't have to specify it in each case. This also means that you would have to remove every instance of the actor in the keyspace. It will function a little differently than this but not too much. 

Can you also get rid of the merge commit before sending again?

**Comment by isaac-gittins-amaysim** [comment]
Hi Aaron,

Thanks for the feedback.

There a few different options:


1)      Remove from all lists, like:

$ repsheet –remove=”1.1.1.1”


2)      Support key globing, like:

$ repsheet –remove=”1.1.1.1*blacklist”


3)      A more verbose interface, like:

$ repsheet –remove-blacklist=”1.1.1.1”

Do you have a preference?

Thanks.
Isaac

**Comment by abedra** [comment]
I think just a general -remove would be good. The typical use case I see is actors being completely removed from the system more than anything.

**Pull request closed without merging**
